# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Superior Flight Training
email: info@superiorflighttraining.net
description: > # this means to ignore newlines until "baseurl:"
  Whether learning to fly for a career, your business or even just for fun, you can achieve your aviation goals in our state of the art 2022 Cessna 172 Skyhawk!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Superior Flight Training
address_line: 282 Airport Rd, Anderson, IN 46017
telephone_number: 1.317.207.9686
fax_number: 1.317.207.9686
company_email: info@superiorflighttraining.net
google_map: https://goo.gl/maps/8FSkQHqaWir6Gss67

# Social Link
facebook_link: https://facebook.com/superiorflightindy
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com
instagram_link: https://instagram.com/superiorflightindy/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
